# Generated by Django 3.2.13 on 2023-12-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advinterface', '0006_auto_20231204_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
