# Generated by Django 3.2.13 on 2023-12-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advinterface', '0008_auto_20231204_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_code',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit_hours',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.CharField(choices=[('communication', 'Communication'), ('mathematics', 'Mathematics'), ('social_and_behavioral_sciences', 'Social and Behavioral Sciences'), ('component_area_option', 'Component Area Option'), ('cis_requirements', 'CIS Requirements'), ('nine_hours_from', 'Nine Hours From'), ('advanced_cidm_electives', 'Advanced CIDM Electives')], max_length=50),
        ),
    ]
