# Generated by Django 3.2.13 on 2023-12-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advinterface', '0009_auto_20231204_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
