# Generated by Django 3.2.13 on 2023-12-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advinterface', '0010_alter_course_class_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_code',
            field=models.CharField(max_length=20),
        ),
    ]
