# Generated by Django 3.2.13 on 2023-11-28 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advinterface', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='name',
            new_name='cname',
        ),
        migrations.RemoveField(
            model_name='class',
            name='major',
        ),
        migrations.AddField(
            model_name='class',
            name='alternate_cname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='alternate_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='code',
            field=models.CharField(default='some_default_value', max_length=255),
        ),
    ]
