# Generated by Django 3.2.13 on 2023-11-28 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advinterface', '0002_auto_20231128_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='cname',
            new_name='classname',
        ),
        migrations.RemoveField(
            model_name='class',
            name='alternate_cname',
        ),
        migrations.RemoveField(
            model_name='class',
            name='alternate_code',
        ),
    ]
