# Generated by Django 3.2.13 on 2023-11-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advinterface', '0004_alter_class_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='code',
            field=models.CharField(default='CIDM', max_length=255),
        ),
    ]
