# Generated by Django 3.2.13 on 2023-11-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advinterface', '0005_alter_class_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='NineHoursFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='CIDM', max_length=255)),
                ('classname', models.CharField(max_length=255)),
                ('credit_hours', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='advisor',
            name='major',
        ),
        migrations.AddField(
            model_name='advisor',
            name='location',
            field=models.CharField(default='CC', max_length=255),
        ),
    ]
