# Generated by Django 3.2.13 on 2023-11-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advinterface', '0006_auto_20231128_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='UCComm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='CIDM', max_length=255)),
                ('classname', models.CharField(max_length=255)),
                ('credit_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UCComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='CIDM', max_length=255)),
                ('classname', models.CharField(max_length=255)),
                ('credit_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UCMathSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='CIDM', max_length=255)),
                ('classname', models.CharField(max_length=255)),
                ('credit_hours', models.IntegerField()),
            ],
        ),
    ]
